# Generated by Django 4.2 on 2023-05-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
        ("service_providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="locations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location",
                to="address.location",
            ),
        ),
    ]
